const chatFeed = document.getElementById('chatFeed');
const userInput = document.getElementById('userInput');
const sendBtn = document.getElementById('sendBtn');
const micBtn = document.getElementById('micBtn');
const apiKeyBtn = document.getElementById('apiKeyBtn');
const welcomeContainer = document.getElementById('welcomeContainer');
const modelBadge = document.querySelector('.model-badge');

// Retrieve stored Gemini API Key
let apiKey = localStorage.getItem('GEMINI_API_KEY') || '';

// API Key Setup Prompt
apiKeyBtn.addEventListener('click', () => {
  const currentKey = localStorage.getItem('GEMINI_API_KEY') || '';
  const input = prompt("Enter your Google Gemini API Key (from aistudio.google.com):", currentKey);
  if (input !== null) {
    apiKey = input.trim();
    localStorage.setItem('GEMINI_API_KEY', apiKey);
    alert(apiKey ? "API Key connected successfully." : "API Key cleared.");
  }
});

// Auto-grow Textarea
userInput.addEventListener('input', () => {
  userInput.style.height = 'auto';
  userInput.style.height = Math.min(userInput.scrollHeight, 140) + 'px';
});

// Suggestion Cards Trigger
document.querySelectorAll('.suggestion-card').forEach(card => {
  card.addEventListener('click', () => {
    const promptText = card.getAttribute('data-prompt');
    userInput.value = promptText;
    handleSend();
  });
});

// --- GOOGLE GEMINI 3.6 FLASH API ENGINE ---
async function fetchGeminiResponse(prompt) {
  if (!apiKey) {
    return "Please set your Gemini API Key by tapping the gear icon (⚙️) at the top right. You can obtain one for free at [Google AI Studio](https://aistudio.google.com/app/apikey).";
  }

  // Active Gemini 3.6 Flash Endpoint
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${apiKey}`;

  const requestBody = {
    contents: [
      {
        role: "user",
        parts: [{ text: prompt }]
      }
    ],
    generationConfig: {
      temperature: 0.7,
      maxOutputTokens: 2048
    }
  };

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody)
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error?.message || `HTTP error ${response.status}`);
    }

    if (data.candidates && data.candidates[0]?.content?.parts[0]?.text) {
      return data.candidates[0].content.parts[0].text;
    } else {
      throw new Error("No response content generated by model.");
    }
  } catch (err) {
    return `**Error reaching Gemini API:** ${err.message}`;
  }
}

// --- TEXT-TO-SPEECH (TTS) ---
function speakText(text) {
  if ('speechSynthesis' in window) {
    window.speechSynthesis.cancel();
    const clean = text.replace(/[*#`_]/g, '').substring(0, 300);
    const utterance = new SpeechSynthesisUtterance(clean);
    utterance.rate = 1.0;
    utterance.pitch = 1.0;
    window.speechSynthesis.speak(utterance);
  }
}

// --- SPEECH RECOGNITION (Microphone) ---
const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
let recognition = null;
let isListening = false;

if (SpeechRecognition) {
  recognition = new SpeechRecognition();
  recognition.continuous = false;
  recognition.lang = 'en-US';

  recognition.onstart = () => {
    isListening = true;
    micBtn.classList.add('active');
  };

  recognition.onresult = (e) => {
    userInput.value = e.results[0][0].transcript;
    handleSend();
  };

  recognition.onerror = () => stopMic();
  recognition.onend = () => stopMic();
}

function stopMic() {
  isListening = false;
  micBtn.classList.remove('active');
}

micBtn.addEventListener('click', () => {
  if (!recognition) {
    alert("Speech recognition is not supported in this browser. Please use Google Chrome.");
    return;
  }
  if (!isListening) recognition.start();
  else recognition.stop();
});

// --- CHAT RENDERING ---
function appendUserMessage(text) {
  if (welcomeContainer) welcomeContainer.style.display = 'none';

  const row = document.createElement('div');
  row.className = 'msg-row user';
  row.innerHTML = `<div class="msg-bubble">${escapeHTML(text)}</div>`;
  chatFeed.appendChild(row);
  chatFeed.scrollTop = chatFeed.scrollHeight;
}

function appendGeminiLoading() {
  const row = document.createElement('div');
  row.className = 'msg-row gemini';
  row.innerHTML = `
    <svg class="gemini-avatar sparkle-icon" viewBox="0 0 24 24">
      <path fill="url(#gemini-grad)" d="M12 2L14.5 9.5L22 12L14.5 14.5L12 22L9.5 14.5L2 12L9.5 9.5L12 2Z"/>
    </svg>
    <div class="msg-bubble">
      <div class="loading-shimmer">
        <div class="shimmer-line"></div>
        <div class="shimmer-line short"></div>
      </div>
    </div>
  `;
  chatFeed.appendChild(row);
  chatFeed.scrollTop = chatFeed.scrollHeight;
  return row;
}

function escapeHTML(str) {
  return str.replace(/[&<>'"]/g, tag => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;'
  }[tag] || tag));
}

async function handleSend() {
  const text = userInput.value.trim();
  if (!text) return;

  appendUserMessage(text);
  userInput.value = '';
  userInput.style.height = 'auto';

  const loadingRow = appendGeminiLoading();
  const responseMarkdown = await fetchGeminiResponse(text);

  const bubble = loadingRow.querySelector('.msg-bubble');
  bubble.innerHTML = (typeof marked !== 'undefined') ? marked.parse(responseMarkdown) : responseMarkdown;

  const tools = document.createElement('div');
  tools.className = 'msg-tools';
  tools.innerHTML = `
    <button class="tool-btn" title="Read aloud">
      <svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor">
        <path d="M3 9v6h4l5 5V4L7 9H3zm13.5 3c0-1.77-1.02-3.29-2.5-4.03v8.05c1.48-.73 2.5-2.25 2.5-4.02zM14 3.23v2.06c2.89.86 5 3.54 5 6.71s-2.11 5.85-5 6.71v2.06c4.01-.91 7-4.49 7-8.77s-2.99-7.86-7-8.77z"/>
      </svg>
    </button>
  `;
  tools.querySelector('button').addEventListener('click', () => speakText(responseMarkdown));
  bubble.appendChild(tools);

  chatFeed.scrollTop = chatFeed.scrollHeight;
}

sendBtn.addEventListener('click', handleSend);
userInput.addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    handleSend();
  }
});
